RotMatrix:
  A_0_0: 0
  A_0_1: -1
  A_1_0: 1
  A_1_1: 0
FallInterval: 0.5
Width: 10
Height: 20
NewBoxLoc:
  X: 5
  Y: 18
LimitHeight: 16
BoxGroupPrefabs:
- - X: -1
    Y: 0
  - X: 0
    Y: 0
  - X: 1
    Y: 0
  - X: 2
    Y: 0
- - X: 0
    Y: 1
  - X: 0
    Y: 0
  - X: 1
    Y: 0
  - X: 2
    Y: 0
- - X: 0
    Y: 1
  - X: 0
    Y: 0
  - X: -1
    Y: 0
  - X: -2
    Y: 0
- - X: 0
    Y: 1
  - X: 0
    Y: 0
  - X: 1
    Y: 0
  - X: 1
    Y: 1
- - X: -1
    Y: 1
  - X: 0
    Y: 1
  - X: 0
    Y: 0
  - X: 1
    Y: 0
- - X: -1
    Y: 0
  - X: 0
    Y: 0
  - X: 0
    Y: 1
  - X: 1
    Y: 1
- - X: -1
    Y: 0
  - X: 0
    Y: 0
  - X: 0
    Y: 1
  - X: 1
    Y: 0
BoxGroupSRS:
- X: 0.5
  Y: -0.5
- X: 1
  Y: 0
- X: -1
  Y: 0
- X: 0.5
  Y: 0.5
- X: 0
  Y: 0
- X: 0
  Y: 0
- X: 0
  Y: 0
